name: Publish
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: |
          npm ci
          npm run build
      - run: |
          git checkout -b "publish-$GITHUB_SHA"
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Publish commit $GITHUB_SHA" || true
          git push --set-upstream origin "publish-$GITHUB_SHA"
      - run: |
          gh pr create --title "Publish commit $GITHUB_SHA" --base main --head "publish-$GITHUB_SHA"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
